% compute kernel between asynchronously observed mRNA samples

function kernelvalue=kernel_async_m(t,tb,Sj,Sk,Dj,Dk,A,L,sigma2);

kernelvalue1=Sj*Sk*sqrt(pi)*A*L*exp((Dk^2)*(L^2)/4)/(Dj+Dk)*...
    exp(((Dk^2)*sigma2-2*Dk)*tb/2)*...
    (exp(((Dk^2)*sigma2+2*Dk)*t/2)*erf((-Dk*(L^2)/2-(1-Dk*sigma2)*tb-(1-Dk*sigma2)*t)/sqrt((L^2)+2*tb*sigma2+2*t*sigma2))...
     -exp(-Dj)*erf((-Dk*(L^2)/2-(1-Dk*sigma2)*tb)/sqrt((L^2)+2*tb*sigma2))...
     +exp(((Dk^2)*sigma2+2*Dk)*t/2)*erf((Dk*(L^2)/2+(1+Dk*sigma2)*t)/sqrt((L^2)+2*t*sigma2))...
     -exp(-Dj)*erf(Dk*L/2));

kernelvalue2=Sj*Sk*sqrt(pi)*A*L*exp((Dj^2)*(L^2)/4)/(Dj+Dk)*...
    exp(((Dj^2)*sigma2-2*Dj)*t/2)*...
    (exp(((Dj^2)*sigma2+2*Dj)*tb/2)*erf((-Dj*(L^2)/2-(1-Dj*sigma2)*t-(1-Dj*sigma2)*tb)/sqrt((L^2)+2*t*sigma2+2*tb*sigma2))...
     -exp(-Dk)*erf((-Dj*(L^2)/2-(1-Dj*sigma2)*t)/sqrt((L^2)+2*t*sigma2))...
     +exp(((Dj^2)*sigma2+2*Dj)*tb/2)*erf((Dj*(L^2)/2+(1+Dj*sigma2)*tb)/sqrt((L^2)+2*tb*sigma2))...
     -exp(-Dk)*erf(Dj*L/2));

kernelvalue=kernelvalue1+kernelvalue2;

