function kernelvalue=kernel_instant_m(t,tb,Sj,Sk,Dj,Dk,A,L,sigma2);

kernelvalue1=Sj*Sk*sqrt(pi)*A*L/2*exp((Dk^2)*(L^2)/4)/(Dj+Dk)*...
    (exp(-Dk*(tb-t))*(erf((tb-t)/L-Dk*L/2)+erf(t/L+Dk*L/2))...
     -exp(-Dk*tb-Dj)*(erf(tb/L-Dk*L/2)+erf(Dk*L/2)));

kernelvalue2=Sj*Sk*sqrt(pi)*A*L/2*exp((Dj^2)*(L^2)/4)/(Dj+Dk)*...
    (exp(-Dj*(t-tb))*(erf((t-tb)/L-Dj*L/2)+erf(tb/L+Dj*L/2))...
     -exp(-Dj*t-Dk)*(erf(t/L-Dj*L/2)+erf(Dj*L/2)));

kernelvalue=kernelvalue1+kernelvalue2;