% compute kernel between asynchronously observed mRNA samples

function kernelvalue=kernel_async_m(t,tb,Sj,Sk,Dj,Dk,A,L,sigma2);

if 1,
kernelvalue1=Sj*Sk*sqrt(pi)*A*L*exp((Dk^2)*(L^2)/4)/(Dj+Dk)*...    
    (exp(-Dk*(tb-t)+(Dk^2)*sigma2/2*(tb+t))*...
     (erf((tb-t -Dk*sigma2*(tb+t) -Dk*(L^2)/2)/sqrt((L^2)+2*tb*sigma2+2*t*sigma2))...
      +erf((Dk*(L^2)/2+(1+Dk*sigma2)*t)/sqrt((L^2)+2*t*sigma2)))...
     -exp(-Dk*tb*(1-Dk*sigma2/2)-Dj)*...
     (erf(((1-Dk*sigma2)*tb-Dk*(L^2)/2)/sqrt((L^2)+2*tb*sigma2))...
      +erf(Dk*L/2)));

kernelvalue2=Sk*Sj*sqrt(pi)*A*L*exp((Dj^2)*(L^2)/4)/(Dk+Dj)*...    
    (exp(-Dj*(t-tb)+(Dj^2)*sigma2/2*(t+tb))*...
     (erf((t-tb -Dj*sigma2*(t+tb) -Dj*(L^2)/2)/sqrt((L^2)+2*t*sigma2+2*tb*sigma2))...
      +erf((Dj*(L^2)/2+(1+Dj*sigma2)*tb)/sqrt((L^2)+2*tb*sigma2)))...
     -exp(-Dj*t*(1-Dj*sigma2/2)-Dk)*...
     (erf(((1-Dj*sigma2)*t-Dj*(L^2)/2)/sqrt((L^2)+2*t*sigma2))...
      +erf(Dj*L/2)));
end;


if 0,
% Just the inner integral...
a=t;
kernelvalue1=Sj*Sk*A*L/2*exp((Dk^2)*(L^2)/4)/(Dj+Dk)*exp(((Dk^2)*sigma2-2*Dk)*tb/2)*...
    (exp(Dk*a)*erf((-(a+Dk*(L^2)/2)+(1-Dk*sigma2)*tb)/sqrt((L^2)+2*tb*sigma2))...
     -exp(-Dj)*erf((-Dk*(L^2)/2+(1-Dk*sigma2)*tb)/sqrt((L^2)+2*tb*sigma2))...
     +exp(Dk*a)*erf(a/L+Dk*L/2)-exp(-Dj)*erf(Dk*L/2));
end;





kernelvalue=kernelvalue1+kernelvalue2;

