% POL2RNASEQTOOLBOXES Toolboxes for the POL2RNASEQ software.

% GPmat
paths={'~/SheffieldML/GPmat/kern/', ...
       '~/SheffieldML/GPmat/gp/', ...
       '~/SheffieldML/GPmat/gpsim/', ...
       '~/SheffieldML/GPmat/optimi/', ...
       '~/SheffieldML/GPmat/ndlutil/', ...
       '~/SheffieldML/GPmat/prior/', ...
       '~/SheffieldML/GPmat/mltools/', ...
       '~/github/pol2rna/matlab/', ...
       '~/mlprojects/matlab/netlab/NETLAB3p3/'}; % NETLAB for dist2.m

addpath(paths{:})
